rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - rbx-2.0

script: "bundle exec rake clean test"
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails2_paperclip_2_3.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails3_paperclip_2_3.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_1_paperclip_2_3.gemfile
